language: cpp
sudo: false

compiler:
  - clang
  
env:
  - CONFIG=Release
  - CONFIG=Release UNITY_BUILD=1
  - CONFIG=Debug
  - CONFIG=Debug UNITY_BUILD=1
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang
      - gcc-4.8
      - g++-4.8
      - libcppunit-dev
      - libboost1.55-all-dev
      
cache:
  - apt: true
  - directories:
    - cmake-3.2.3-Linux-x86_64
    
before_install:
# workaround for not having CMake 3.2
  - if [ ! -d "cmake-3.2.3-Linux-x86_64/bin" ]; then
      wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz;
    fi

before_script:
  - mkdir build
  - cd build
  - ../cmake-3.2.3-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
  - if [ $UNITY_BUILD ]; then make -j2 all_unity; else make -j2; fi
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log

notifications:
  email:
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
