language: cpp
sudo: false

compiler:
  - clang

env:
  - CONFIG=Release
  - CONFIG=Debug

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang
      - gcc-4.8
      - g++-4.8
      - libcppunit-dev
      - libboost1.55-all-dev

cache:
  - apt: true
  - directories:
    - cmake-3.4.0-Linux-x86_64

before_install:
# workaround for not having CMake 3.2
  - if [ ! -d "cmake-3.2.3-Linux-x86_64/bin" ]; then
      wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.4.0-Linux-x86_64.tar.gz;
    fi

before_script:
  - mkdir build
  - cd build
  - ../cmake-3.4.0-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=$CONFIG ..

script:
  - make -j2
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log

notifications:
  email:
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
  slack:
    rooms:
      - kazdragon:E8B4Cs4p3TiVLqHAq8wYYTr3#ci
